//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAP_Backend_Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EssayAnswer
    {
        public int EQuestionId { get; set; }
        public int AccountIdRespondent { get; set; }
        public string EAnswerContent { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
