//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAP_Backend_Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EssayQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EssayQuestion()
        {
            this.EssayAnswers = new HashSet<EssayAnswer>();
        }
    
        public int EQuestionId { get; set; }
        public int TestsId { get; set; }
        public string EQuestionTitle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EssayAnswer> EssayAnswers { get; set; }
        public virtual Test Test { get; set; }
    }
}
