//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAP_Backend_Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Learner
    {
        public int LearnerId { get; set; }
        public int AccountIdLearner { get; set; }
        public int ProgramId { get; set; }
        public int AccountIdApprover { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Program Program { get; set; }
    }
}
