//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAP_Backend_Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultipleChoiceQuestion
    {
        public int MCQuestionId { get; set; }
        public int TestsId { get; set; }
        public string MCQuestionTitle { get; set; }
        public string Content1 { get; set; }
        public byte[] Content2 { get; set; }
        public string Content3 { get; set; }
        public string Content4 { get; set; }
        public string Answer { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
