//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAP_Backend_Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultipleChoiceQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MultipleChoiceQuestion()
        {
            this.MultipleChoiceAnswers = new HashSet<MultipleChoiceAnswer>();
        }
    
        public int MCQuestionId { get; set; }
        public int TestsId { get; set; }
        public string MCQuestionTitle { get; set; }
        public string Content1 { get; set; }
        public string Content2 { get; set; }
        public string Content3 { get; set; }
        public string Content4 { get; set; }
        public string Answer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MultipleChoiceAnswer> MultipleChoiceAnswers { get; set; }
        public virtual Test Test { get; set; }
    }
}
